# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('target', models.CharField(choices=[('ACA', 'Academic'), ('GAM', 'Gaming'), ('SCL', 'Social'), ('SCT', 'Society')], max_length=3)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
