# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 22:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20160917_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='finish',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 17, 23, 13, 57, 172164)),
        ),
        migrations.AlterField(
            model_name='eventsignup',
            name='comment',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
