# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 13:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20160918_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='finish',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 18, 14, 14, 31, 336873, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='eventsignup',
            name='signup_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
