# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 10:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20160918_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.EventType'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='finish',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 19, 11, 54, 2, 935656)),
        ),
    ]
