# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 17:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20160920_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='finish',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 21, 18, 21, 40, 142886, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='signup_close',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 21, 18, 21, 40, 142964, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='signup_limit',
            field=models.IntegerField(help_text='Enter 0 for unlimited signups, -1 for no signups', verbose_name='Signup limit'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='signup_open',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
