# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 18:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20160921_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='finish',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 21, 19, 44, 2, 40756, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='signup_close',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 21, 19, 44, 2, 40832, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventsignup',
            name='comment',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
