# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 19:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20160921_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='finish',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 22, 20, 28, 38, 268675, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='signup_close',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 22, 20, 28, 38, 268752, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventsignup',
            name='comment',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
