# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 20:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('events', '0017_auto_20160922_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsArchivePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='finish',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 22, 21, 59, 53, 179554, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='signup_close',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 22, 21, 59, 53, 179630, tzinfo=utc)),
        ),
    ]
