# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 12:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20160928_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='finish',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 8, 13, 36, 0, 840321, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='signup_close',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 8, 13, 36, 0, 840429, tzinfo=utc)),
        ),
    ]
