# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_mail_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='date_subscribed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mail',
            name='sender',
            field=models.EmailField(default='noreply@uwcs.co.uk', max_length=254),
        ),
    ]
