# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_subscription_unsubscribe_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='sender_email',
            field=models.EmailField(default='newsletter@uwcs.co.uk', max_length=254),
        ),
    ]
