# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 19:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160914_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseaccount',
            name='name',
            field=models.CharField(error_messages={'regex': 'The name must contain all lowercase alphanumeric characters'}, max_length=30, validators=[django.core.validators.RegexValidator(code='regex', regex=re.compile('^[a-z0-9]+$', 32))]),
        ),
        migrations.AlterField(
            model_name='shellaccount',
            name='name',
            field=models.CharField(error_messages={'regex': 'The name must contain all lowercase alphanumeric characters'}, max_length=30, validators=[django.core.validators.RegexValidator(code='regex', regex=re.compile('^[a-z0-9]+$', 32))]),
        ),
    ]
