# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160914_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='compsocuser',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='compsocuser',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='compsocuser',
            name='nightmode_on',
            field=models.BooleanField(default=False),
        ),
    ]
