# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170623_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compsocuser',
            name='nightmode_on',
            field=models.BooleanField(default=False, help_text='Enable night mode whenever you are logged into UWCS - overrides the nightmode switch in the footer'),
        ),
    ]
