# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160719_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='description',
            field=models.TextField(default='', max_length=400),
        ),
    ]
