# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_sponsor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='sponsor_image',
        ),
    ]
