# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_homepage_sponsor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='primary_sponsor',
            field=models.BooleanField(default=False),
        ),
    ]
