# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_sponsor_primary_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitch_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
