# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20160814_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='body',
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='intro',
            field=models.TextField(help_text='This is displayed on the home and blog listing pages'),
        ),
    ]
