# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 18:54
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20160814_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(help_text='This is displayed on the home and blog listing pages'),
        ),
    ]
