# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 12:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('events', '0001_initial'),
        ('blog', '0020_aboutpage_full_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.StreamField((('h2', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title')), ('h3', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title')), ('h4', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('pullquote', wagtail.wagtailcore.blocks.StructBlock((('quote', wagtail.wagtailcore.blocks.TextBlock('quote title')), ('attribution', wagtail.wagtailcore.blocks.CharBlock())))), ('document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse')), ('code', wagtail.wagtailcore.blocks.StructBlock((('language', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('bash', 'Bash/Shell'), ('c', 'C'), ('cmake', 'CMake'), ('cpp', 'C++'), ('csharp', 'C#'), ('css', 'CSS'), ('go', 'Go'), ('haskell', 'Haskell'), ('haxe', 'Haxe'), ('html', 'HTML'), ('java', 'Java'), ('js', 'JavaScript'), ('json', 'JSON'), ('kotlin', 'Kotlin'), ('lua', 'Lua'), ('make', 'Makefile'), ('perl', 'Perl'), ('perl6', 'Perl 6'), ('php', 'PHP'), ('python', 'Python'), ('python3', 'Python 3'), ('ruby', 'Ruby'), ('sql', 'SQL'), ('swift', 'Swift'), ('xml', 'XML')])), ('code', wagtail.wagtailcore.blocks.TextBlock()))))))),
                ('description', wagtail.wagtailcore.fields.RichTextField(max_length=200)),
                ('start', models.DateTimeField(default=datetime.datetime.now)),
                ('finish', models.DateTimeField(default=datetime.datetime(2016, 9, 17, 13, 37, 24, 158262))),
                ('display_from', models.DateTimeField(default=datetime.datetime.now, help_text='Controls when the event will be visible in event listings', verbose_name='Display from')),
                ('cancelled', models.BooleanField()),
                ('signup_limit', models.IntegerField(help_text='Enter 0 for unlimited signups', verbose_name='Signup limit')),
                ('signup_open', models.DateTimeField()),
                ('signup_close', models.DateTimeField()),
                ('signup_freshers_open', models.DateTimeField(blank=True, help_text='Set a date for when freshers may sign up to the event, leave blank if they are to sign up at the                   same time as everyone else')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='events.EventType')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
