# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 12:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20160917_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='location',
            field=models.CharField(default='Department of Computer Science', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='finish',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 17, 13, 43, 11, 659956)),
        ),
    ]
