# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 12:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20160917_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='facebook_link',
            field=models.URLField(blank=True, help_text='A link to the associated Facebook event if one exists', verbose_name='Facebook event'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='finish',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 17, 13, 46, 34, 653423)),
        ),
    ]
