# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('blog', '0024_auto_20160917_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='EventPage',
        ),
    ]
