# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('blog', '0025_auto_20160917_1617'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventsIndexPage',
        ),
    ]
