# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20160919_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='full_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
