# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20160922_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Post date'),
        ),
    ]
