# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('blog', '0030_auto_20161017_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='nightmode_image',
            field=models.ForeignKey(blank=True, help_text='This image will be displayed in all sponsor display locations accross the website in night mode', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
