# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_sponsor_nightmode_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='email_sponsor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='email_text_markdown',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
