# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20171016_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='email_text_markdown',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
