# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20171016_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='email_sponsor',
            field=models.BooleanField(default=True, help_text='Should this sponsor be included in the newsletters?'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='email_text_markdown',
            field=models.CharField(help_text='The text content in our newsletter emails. Is required to be valid markdown', max_length=1000),
        ),
    ]
