# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20171016_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='email_text_markdown',
            field=models.TextField(help_text='The text content in our newsletter emails. Is required to be valid markdown', max_length=4000, verbose_name='Email text'),
        ),
    ]
