# Generated by Django 2.2.3 on 2019-07-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20171016_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='privacy_policy_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
